name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: mvn --batch-mode --update-snapshots verify
   # - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: target  
  
  
#     - name: Build	
#       uses: qcastel/github-actions-maven/actions/maven@master
#       with:
#         maven-args: "clean install"
      
    - name: env
      run: env  
      
    - name: Docker Build Tag Publish
      uses: zenato/docker-action@master
      with:
          username: 100000127754
          password: luoxun007
          repository: xun-demo/springdemo
          registry: ccr.ccs.tencentyun.com
          tag: 1.0
