name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
  
    - name: Build	
      uses: qcastel/github-actions-maven/actions/maven@master
      with:
        maven-args: "clean install"
      
    - name: env
      run: env  
      
    - name: Docker Build Tag Publish
      uses: zenato/docker-action@master
      with:
          username: 100000127754
          password: luoxun007
          repository: xun-demo/springdemo
          registry: ccr.ccs.tencentyun.com
          tag: 1.0
